#!/bin/bash
# Setting the environment variable CFILE to the value "main.c"
export CFILE=main.c
# Invoking the GCC compiler with the -S option to perform assembly
gcc -S -Wall -Werror -Wextra -pedantic -std=gnu89 $CFILE
